/*
      Copyright 2011 / 2012
          Matthias Ehmann,
          Michael Gerhaeuser,
          Carsten Miller,
          Heiko Vogel,
          Alfred Wassermann

      This file is part of the JSXGraph GUI project.
      This code isn't licensed yet.
 */

GUI.Lang = { };

GUI.Lang.Map = [[ 'de', 'en', 'fr', 'es', 'pt', 'it' ], [ 'Deutsch', 'English', 'Français', 'Español', 'Português', 'Italiano' ]];

GUI.Lang.strings = {
    'ablateOnIntersection': [ 'Abtragen auf', 'Copy on:', 'Copier vers', 'Copiar en', 'Copiar em', 'Copia verso' ],
    'ablate_objects': [ 'Objekte abtragen', 'Copy objects', 'Copier les objets', 'Copiar objetos', 'Copiar objetos', 'Copia gli oggetti' ],
    'ablation_instruct': [ 'Klicke auf das Objekt (Kreis / Strecke), das abgetragen werden soll.', 'Click on the object (circle / line segment) you want to copy.', 'Cliquer sur l\'objet à copier (cercle/droite/segment).', 'Clic en objeto (círculo, línea, segmento) que desea copiar', 'Clique no objeto (círculo / reta /segmento) que você deseja copiar.', 'Clicca sull\'oggetto da copiare (circonferenza, linea o segmento)' ],
    'actions': [ 'Aktions-Menü', 'Actions menu', 'Menu des actions', 'Menú de acciones', 'Menu de ações', 'Menù delle azioni' ],
    'anglesector_selection': [ 'Markiere: Punkt - Scheitel - Punkt', 'Mark: Point - Vertex - Point', 'Marquer les 3 points qui définissent le secteur angulaire', 'Marcar tres puntos para definir sector angular', 'Marque três pontos para definir o setor angular.', 'Indica: Punto, Vertice, Punto' ],
    'angle_button_rightangle': [ 'Rechter Winkel', 'Right angle', 'Angle droit', 'Ángulo recto', 'Ângulo reto', 'Angolo retto' ],
    'angle_element': [ 'Winkel', 'Angle', 'Angle', 'Ángulo', 'Ângulo', 'Angolo' ],
    'angle_measure': [ 'Winkel messen', 'Measure angle', 'Mesurer angle', 'Medir ángulo', 'Medida de ângulo', 'Misura l\'angolo' ],
    'angle_sector': [ 'Winkelsektor', 'Angle sector', 'Secteur angulaire', 'Sector angular', 'Setor angular', 'Segno di angolo' ],
    'arrow': [ 'Pfeilspitzen', 'Arrow heads', 'Flèches', 'Cabeza de flechas', 'Tipos de setas', 'Freccia' ],
    'axis': [ 'Achse', 'Axis', 'Axe', 'Eje', 'Eixo', 'Asse' ],
    'axispoint': [ 'Achsenpunkt', 'Axis point', 'Point de l\'axe', 'Punto en eje', 'Ponto do eixo', 'Punto dell\'asse' ],
    'axis_scale': [ 'Skalierung', 'Scale', 'Échelle', 'Escala', 'Escala', 'Scala' ],
    'axis_visibility': [ 'Achsen', 'Axes', 'Axes', 'Ejes', 'Eixos', 'Assi' ],
    'back': [ 'Zurück', 'Back', 'Retour', 'Volver', 'Voltar', 'Indietro' ],
    'backspace': [ 'Backspace', 'Backspace', 'Retour Arrière', '', '', 'Tasto indietro' ],
    'bgnd': [ 'Hintergrundbild', 'Background image', '', '', '', 'Immagine di sfondo' ],
    'bisector': [ 'Winkelhalbierende', 'Angular bisector', 'Bissectrice', 'Bisectriz', 'Bissetriz', 'Bisettrice' ],
    'board_clear_all': [ 'Alles löschen', 'Remove all', 'Tout effacer', 'Eliminar todo', 'Remover tudo', 'Elimina tutto' ],
    'bottom': [ 'Unten', 'Bottom', 'Bas', 'Abajo', 'Embaixo', 'Sotto' ],
    'cancel': [ 'Abbrechen', 'Cancel', 'Annule', 'Cancelar', 'Cancelar', 'Annulla' ],
    'cantoverwrite': [ 'Datei kann nicht überschrieben werden!', 'File already exists and can not be overwritten!', 'Le fichier existe déjà et ne peut pas être écraser !', 'Archivo existente y no puede volver a grabarse', 'O arquivo já existe e não pode ser sobrescrito.', 'Il file è già esistente e non può essere sovrascritto' ],
    'cas': [ 'Punkt', 'Point', 'Point', 'Punto', 'Ponto', 'Punto' ],
    'center': [ 'Zentrieren', 'Center', 'Centrer', 'Centro', 'Centro', 'Centro' ],
    'chooseformat': [ 'Sie müssen mindestens ein Dateiformat auswählen.', 'You have to choose at least one file format.', 'Vous devez choisir au moins un format de fichier', 'Escoger al menos un formato de archivo', 'Você deve escolher pelo menos um formato de arquivo', 'Devi scegliere un formato di file' ],
    'choosesector': [ 'Art des Sektors', 'Choose the sector type', 'Choisir le type de secteur', 'Escoger el tipo de sector', 'Escolha o tipo de setor', 'Scegli il tipo di settore' ],
    'circle': [ 'Kreis', 'Circle', 'Cercle', 'Círculo', 'Círculo', 'Circonferenza' ],
    'circle2points': [ 'Kreis (Mittelpunkt - Punkt)', 'Circle (2P)', 'Cercle (2P)', 'Círculo (2 puntos)', 'Círculo (2P)', 'Circonferenza (3P.ti)' ],
    'circlesector_selection': [ 'Markiere: Punkt - Mittelpunkt - Punkt', 'Mark: Point - Midpoint- Point', 'Marquer les trois points qui définissent le secteur circulaire.', 'Marcar tres puntos para definir sector circular', 'Marque os três pontos para definir o setor circular.', 'Indica: punto, centro, punto' ],
    'circle_sector': [ 'Kreissektor', 'Circle sector', 'Secteur circulaire', 'Sector circular', 'Setor circular', 'Settore circolare' ],
    'clear': [ 'Lösche Schriftzug', 'Delete Stroke', 'Effacer l\'écriture', '', '', 'Canc.' ],
    'clear_reassure': [ 'Wirklich alle Objekte löschen?', 'Do you really want to delete all objects on the board?', 'Voulez-vous vraiment supprimer tous les objets ?', '¿Realmente desea eliminar todos los objetos del plano? ', 'Você deseja realmente apagar todos os objetos?', 'Vuoi veramente eliminare gli oggetti?' ],
    'clear_traces': [ 'Spuren löschen', 'Clear traces', 'Effacer traces', 'Borrar trazas', 'Limpar traços', 'Elimina tracce' ],
    'clicktoconnect': [ 'Verbindung herstellen mit', 'Connect with', 'Connecter avec', 'Conectar con', 'Conectar com', 'Collega con' ],
    'clone': [ 'Klonen', 'Clone', 'Cloner', 'Clonar', 'Clonar', 'Clona' ],
    'colors': [ 'Farben', 'Colors', 'Couleurs', 'Colores', 'Cores', 'Colori' ],
    'confirmoverwrite': [ 'Datei existiert bereits, überschreiben?', 'File already exists. Overwrite?', 'Le fichier existe déjà, écraser ?', 'Archivo existente, ¿grabar otra vez?', 'O arquivo já existe. Sobrescrever?', 'File esistente, sovrascrivo?' ],
    'confirmreset': [ 'Bist du sicher? Es werden alle Einstellungen und Konstruktionen gelöscht!', 'Are you sure? All settings and constructions will be deleted!', 'Êtes-vous sûr? Tous les paramètres et les constructions seront effacés.', '¿Está seguro? Todas las configuraciones y objetos serán eliminados', 'Você tem certeza? Todas as configurações e construção serão apagadas!', 'Vuoi veramente eliminare tutte le costruzioni e la configurazione?' ],
    'conic': [ 'Kegelschnitt', 'Conic', 'Conique', 'Cónica', 'Cônica', 'Conica' ],
    'connecting': [ 'Verbinde mit Cloud-Speicher.', 'Connecting to storage provider', 'Connexion au service de stockage en ligne', 'Conectando con el proveedor de almacenamiento', 'Conectando-se com o servidor', 'Accesso al servizio cloud' ],
    'construct_mode': [ 'Konstruktionsmodus aktivieren', 'Activate Construct-Mode', 'Activer le mode construction', 'Activar modo construcción', 'Ativar Modo-de-Construção', 'Attiva la modalità costruzione' ],
    'continue': [ 'Weiter', 'Continue', 'Continuer', 'Terminar autenticación', 'Terminar autenticação.', 'Continua' ],
    'control_boardprop': [ 'Eigensch.', 'Prop.', 'Prop.', 'Propiedades', 'Prop.', 'Prop.' ],
    'control_construct': [ 'Konstr.', 'Constr.', 'Constr.', 'Construir', 'Construir', 'Costr.' ],
    'control_drag': [ 'Ziehen', 'Drag', 'Draguer', 'Arrastrar', 'Arrastar', 'Trascina' ],
    'control_redo': [ 'Vor', 'Redo', 'Refaire', 'Rehacer', 'Refazer', 'Rifai' ],
    'control_tools': [ 'Mehr', 'More', 'Plus', 'Más', 'Mais', 'Altri' ],
    'control_undo': [ 'Zurück', 'Undo', 'Défaire', 'Deshacer', 'Desfazer', 'Disfa' ],
    'coords': [ 'Koordinaten', 'Coordinates', 'Coordonnées', 'Coordenadas', 'Coordenadas', 'Coordinate' ],
    'copy_instruct': [ 'Klicke auf das Objekt, das kopiert werden soll.', 'Click on the object you want to copy.', 'Cliquer sur un objet à copier.', 'Clic en el objeto a copiar', 'Clique no objeto que você deseja copiar.', 'Clicca su un oggetto da copiare' ],
    'copy_objects': [ 'Objekt kopieren', 'Copy objects', 'Copier les objets', 'Copiar objetos', 'Copiar objetos', 'Copia oggetti' ],
    'corners': [ 'Eckenanzahl (>=3 und <=35)', 'Number of corners (>2 and <36)', 'Nombre de sommets (>=3 et <=35)', 'Número de vértices (mayot que 2 y menor que 36)', 'Número de vértices (> 2 e < 36)', 'Numero dei vertici (3<=n<=35)' ],
    'corner_amount': [ 'Eckenzahl: mindestens 3, höchstens 35', 'The number of corners should be >= 3 and <= 35', 'Le nombre de sommets doit être >=3 et <=35', 'El número de vértices debería ser mayor o igual a 3 y menor o igual a 35', 'O número de vértices deve ser >= 3 e <= 35', 'Il numero dei vertici dev\'essere compreso tra 3 e 35 estremi inclusi' ],
    'cursor': [ 'Fadenkreuz', 'Crosshair', 'Réticule (pointeur croix)', 'Cruz', 'Cruz', 'Mirino' ],
    'curve': [ 'Kurve', 'Curve', 'Courbe', 'Curva', 'Curva', 'Curva' ],
    'del': [ 'Löschen', 'Delete', 'Effacer', 'Eliminar', 'Apagar', 'Elimina' ],
    'delete_all': [ 'Alles löschen', 'Delete All', 'Effacer tout', '', '', 'Elimina tutto' ],
    'delete_reassure': [ 'Diese Konstruktion wirklich löschen?', 'Do you really want to delete this construction?', 'Voulez-vous vraiment supprimer cette construction?', '¿Realmente desea eliminar esta construcción?', 'Você deseja realmente apagar esta construção?', 'Vuoi veramente eliminare la costruzione?' ],
    'del_instruct': [ 'Klicke auf das Objekt, das gelöscht werden soll.', 'Click on the object you want to delete.', 'Cliquer sur l\'objet à supprimer', 'Clic en el objeto a eliminar', 'Clique no objeto que você deseja apagar.', 'Clicca sull\'oggetto da eliminare' ],
    'del_objects': [ 'Objekte löschen', 'Delete objects', 'Supprimer les objets', 'Eliminar objetos', '', 'Elimina oggetti' ],
    'drag_file': [ 'Ziehe eine GEONExT- oder sketchometry-Konstruktion in dieses Feld um sie Ihrer Galerie hinzuzufügen.', 'Drop a GEONExT or sketchometry file here to import it.', 'Lâcher ici un fichier GEONEXT ou sketchometry pour l\'importer dans votre galerie.', 'Dejar aquí un archivo GEONExT o Sketchometry para importarlo', 'Arraste um arquivo GEONExT ou Sketchometry aqui para importá-lo.', 'Rilascia un file GEONExT o sketchometry per importarlo' ],
    'drag_mode': [ 'Zugmodus aktivieren', 'Activate Drag-Mode', 'Activer le mode draguer', 'Activar modo arrastrar', 'Ativar Modo-de-Arraste', 'Attiva la modalità trascinamento' ],
    'drawGlider': [ 'Platziere Gleiter auf', 'Place glider on:', 'Placer un glisseur', 'Colocar punto sobre:', 'Colocar marca em:', 'Punto su:' ],
    'element_opacity': [ 'Fülltransparenz', 'Fill opacity', 'Opacité', 'Transparencia', 'Transparência', 'Opacità' ],
    'element_size': [ 'Größe', 'Size', 'Taille', 'Tamaño', 'Tamanho', 'Dimensione' ],
    'emptyfolder': [ 'Leerer Ordner', 'Empty folder', 'Dossier vide', 'Carpeta vacía', 'Arquivo vazio', 'Cartella vuota' ],
    'english': [ 'Englisch', 'English', 'Anglais', 'Inglés', 'Inglês', 'Inglese' ],
    'exp': [ 'Export', 'Export', 'Exporter', 'Exportar', 'Exportar', 'Esporta' ],
    'expo': [ 'Exportieren in die Cloud', 'Export to the cloud', 'Exporter vers le stockage en ligne', 'Exportar a la nube', 'Exportar para a nuvem', 'Esporta verso il servizio cloud' ],
    'fill_settings': [ 'Fülloptionen', 'Fill settings', 'Remplissage', 'Completar los ajustes', 'Definir configurações', 'Riempimento' ],
    'finishauth': [ 'Authentifizierung abschließen', 'Finish authentication.', 'Finir l\'authentification', 'Terminar autenticación', 'Terminar autenticação.', 'Completa l\'autenticazione' ],
    'fixed_glider': [ 'Fixer Gleiter', 'Fixed glider', 'Glisseur fixe', 'Deslizador fijo', 'Marca fixa', 'Cammino fisso' ],
    'fixed_point': [ 'Fixer Punkt', 'Fixed point', 'Point fixe', 'Punto fijo', 'Ponto fixo', 'Punto fisso' ],
    'free': [ 'Frei', 'Free', 'Libre', 'Libre', 'Livre', 'Libera' ],
    'freeGlider': [ 'Gleiter → Freier Punkt ...', 'Glider → Free point ...', 'Glisseur → point libre', 'Punto en objeto → Punto libre...', 'Marca → Ponto livre ...', 'Libera dal cammino' ],
    'freePoint': [ 'Freier Punkt', 'Free point', 'Point libre', 'Punto libre', 'Ponto livre', 'Punto libero' ],
    'function_plot': [ 'Funktionsgraph', 'Function plot', 'Graphe d\'une fonction', 'Graficar función', 'Gráfico de função', 'Grafico di funzione' ],
    'gallery': [ 'Galerie', 'Gallery', 'Galerie', 'Galería', 'Galeria', 'Galleria' ],
    'german': [ 'Deutsch', 'German', 'Allemand', 'Alemán', 'Alemão', 'Tedesco' ],
    'glider': [ 'Gleiter', 'Glider', 'Glisseur', 'Punto en objeto', 'Marca', 'Punto su un cammino' ],
    'glider_instruct': [ 'Objekt an gewünschten Ort ziehen.', 'Release your finger / the mouse button on the object, where you want to place the glider.', 'Relâcher le doigt/la souris sur l\'objet où sera placé le glisseur.', 'Toque con su dedo (presione el botón del mouse) sobre el lugar del objeto onde quiere colocar la marca', 'Pressione o seu dedo / botão do mouse sobre o lugar do objeto onde você quer colocar a marca', 'Rilascia per obbligare su un cammino' ],
    'graphlist': [ 'Funktions-Liste', 'Function list', 'Liste de la fonction', '', '', 'Elenco delle funzioni' ],
    'grid_snap_to_grid': [ 'Einrast. Gitter', 'Snap grid', 'Capture grille', 'Fijar a la cuadrícula', 'Capturar malha', 'Metti sulla griglia' ],
    'grid_snap_to_point': [ 'Einrast. Pkt.', 'Snap points', 'Capture points', 'Fijar puntos', 'Capturar pontos', 'Metti sui punti' ],
    'grid_visible': [ 'Zeige Gitter', 'Show grid', 'Voir grille', 'Exhibir cuadrícula', 'Exibir malha', 'Griglia' ],
    'help': [ 'Hilfe', 'Help', 'Aide', 'Ayuda', 'Ajuda', 'Aiuto' ],
    'hide': [ 'Versteck.', 'Hide', 'Cacher', 'Ocultar', 'Esconder', 'Nascondi' ],
    'hide_instruct': [ 'Klicke auf das Objekt, das angezeigt / versteckt werden soll.', 'Click on the object you want to (un-)hide.', 'Cliquer sur l\'objet à cacher/montrer.', 'Clic en objeto a (des)ocultar', 'Clique no objeto que você quer esconder / exibir.', 'Clicca sull\'oggetto per mostrare o nascondere' ],
    'hide_objects': [ 'Objekte verstecken', 'Hide objects', 'Cacher des objets', 'Objetos ocultos', 'Esconder objetos', 'Nascondi oggetti' ],
    'hwr': [ 'Handschrift-Erkennung', 'Hand-Writing-Recognition', 'Reconnaissance d\'écriture', '', '', 'Riconoscimento scrittura' ],
    'identifier': [ 'Bezeichner', 'Identifier', 'Identifier', 'Identificar', 'Identificar', 'Identifica' ],
    'img': [ 'Bild', 'Image', 'Image', 'Imagen', 'Imagem', 'Immagine' ],
    'imp': [ 'Import', 'Import', 'Importer', 'Importar', 'Importar', 'Importa' ],
    'impo': [ 'Importieren aus der Cloud', 'Import from the cloud', 'Importer depuis le stockage en ligne', 'Importar desde la nube', 'Importar da nuvem', 'Importa da cloud' ],
    'intersect': [ 'Schnittpunkt', 'Intersection point', 'Point intersection', 'Intersección punto', 'Interseção pontos', 'Punto di intersezione' ],
    'label_settings': [ 'Texteigenschaften', 'Label settings', 'Paramètres des étiquettes', 'Ajustes de la etiqueta', 'Configurações de rótulos', 'Dimensione' ],
    'label_visible': [ 'Zeige Beschriftung', 'Show label', 'Montrer l\'étiquette', 'Exhibir rótulos', 'Exibir rótulo', 'Mostra il nome' ],
    'language': [ 'Sprache', 'Language', 'Langage', 'Lenguaje', 'Idioma', 'Lingua' ],
    'left': [ 'Links', 'Left', 'Gauche', 'Izquierda', 'Esquerda', 'Sinistra' ],
    'leftrightmode': [ 'Links- / Rechtshändermodus', 'Left/Right hand mode', 'Mode main gauche/droite', 'Modo mano izquierda (derecha)', 'Modo mão esquerda/direita', 'Modalità mano destra/sinistra' ],
    'len': [ 'Länge', 'Length', 'Longueur', 'Largo', 'Comprimento', 'Lunghezza' ],
    'length_measure': [ 'Längenmessung', 'Measure length', 'Mesurer une longueur', 'Medir longitud', 'Medida de comprimento', 'Misura della lunghezza' ],
    'line': [ 'Gerade', 'Line', 'Droite', 'Recta', 'Reta', 'Retta' ],
    'line_button': [ 'Streckenenden', 'Line endings', 'Segment extrémités', 'Marcación de rectas', 'Marcação de retas', 'Prolunga' ],
    'line_segment': [ 'Strecke', 'Segment', 'Segment', 'Segmento', 'Segmento', 'Segmento' ],
    'loggedinas': [ 'Eingeloggt als', 'Logged in as', 'Connecté en tant que', 'Inició sesión como ', 'Registrado como', 'Connessione come' ],
    'login': [ 'Beginne Authentifizierung (öffnet neues Fenster).', 'Start authentication process (opens new window).', 'Début du processus d\'authentification  (ouvre une nouvelle fenêtre).', 'Comenzar proceso de autenticación (abrirá una nueva ventana)', 'Iniciar processo de autenticação (uma nova janela será aberta)', 'Inizio del processo di autenticazione in una nuova finestra' ],
    'logout': [ 'Logout', 'Logout', 'Déconnecté', 'Cerrar sesión', 'Sair', 'Chiudi' ],
    'magnify': [ 'Lupe', 'Magnifier', 'Loupe', 'Lupa', 'Lente de aumento', 'Ingrandisci' ],
    'mark_glider_object': [ 'Markiere den Ort für den Gleiter.', 'Mark the object on which you want to place the glider.', 'Marquer lobjet sur lequel place un glisseur.', 'Marcar el objeto al que pertenecerá el punto', 'Marque o objeto no qual você deseja colocar a marca.', 'Indica il cammino obbligato per il punto' ],
    'max_value': [ 'Maximalwert', 'Maximal value', '', '', '', 'Valore massimo' ],
    'measure': [ 'Messung', 'Measure', 'Mesurer', 'Medir', 'Medir', 'Misura' ],
    'measure_angle': [ 'Markiere einen angezeigten Winkel oder drei Punkte zum Messen des Winkels.', 'Select either an angle object or three points to measure the corresponding angle value.', 'Sélectionner soit un angle, soit trois points pour obtenir la mesure de cet angle.', 'Seleccionar tres puntos para obtener la correspondiente medida angular', 'Selecione ou um ângulo ou três pontos para medir o ângulo correspondente.', 'Seleziona un angolo (o tre punti) per misurarlo' ],
    'measure_dist': [ 'Markiere zwei Punkte oder ein Geradenstück zum Messen des Abstands oder der Länge.', 'Select either 2 points for measuring the distance between them or a line segment to measure its length.', 'Sélectionner soit 2 points pour obtenir leur distance, soit un segment pour obtenir sa longueur.', 'Seleccionar dos puntos para medir la distancia entre ellos ó el segmento que los une para medir su longitud', 'Selecione dois pontos para medir a distância entre eles ou segmento de reta para medir o seu comprimento.', 'Indica due punti o un segmento per calcolarne distanza o lunghezza' ],
    'measure_instruct': [ 'Wählen Sie das/die zu messende/n Objekt/e aus ...', 'Choose the object(s) to be measured ...', 'Choisir le ou les objets à mesurer', '', '', 'Scegli gli oggetti da misurare' ],
    'measure_instruction': [ 'Markiere einen Winkel-, Kreissektor oder ein Geradenstück, um dessen Länge zu messen.', 'Mark an angle, arc or segment to measure its length.', 'Marquer un angle, un arc ou un segment pour le mesurer.', '', '', 'Indica un angolo, un arco o un segmento per misurarlo' ],
    'measure_sector': [ 'Markiere einen Kreissektor, um dessen Bogenlänge zu messen.', 'Select a circle sector to measure the length of its arc.', 'Sélectionner un secteur circulaire pour mesurer la longueur de son arc. ', 'Seleccionar un sector circular para medir la longitud de su arco', 'Selecione um setor circular para medir o comprimento de seu arco.', 'Seleziona un settore circolare per misurarne l\'arco' ],
    'measure_slider': [ 'Wähle einen Schieberegler, um dessen Wert zu verwenden.', 'Select a slider to measure its value.', 'Sélectionner un curseur pour mesurer sa valeur.', 'Seleccionar un deslizador para obtener su valor', 'Selecione um controle deslizante para obter o seu valor.', 'Seleziona un cursore per assegnare il valore' ],
    'midpoint': [ 'Mittelpunkt', 'Midpoint', 'Milieu', 'Punto medio', 'Ponto médio', 'Punto medio' ],
    'minus': [ 'Verringern', 'Decrease', 'Diminuer', 'Decrementa', 'Diminuir', 'Diminuisci' ],
    'min_value': [ 'Minimalwert', 'Minimal value', '', '', '', 'Valore minimo' ],
    'mir1_instruct': [ 'Markiere eine Spiegelachse.', 'Click on the object which should act as mirror.', 'Cliquer sur l\'objet qui sera axe de la symétrie (réflexion).', 'Clic en el objeto que será eleje de reflexión', 'Clique no objeto que será o centro da reflexão.', 'Clicca sull\'oggetto che rifletterà' ],
    'mir2_instruct': [ 'Markiere das Objekt, das gespiegelt werden soll.', 'Click on the object you want to mirror.', 'Cliquer sur l\'objet dont le symétrique est à construire.', 'Clic en el objeto que desea reflejar', 'Clique no objeto que você deseja refletir.', 'Clicca sull\'oggetto da riflettere' ],
    'mirror_objects': [ 'Objekte spiegeln', 'Mirror objects', 'Objets symétriques', 'Objeto reflejado', 'Refletir objetos', 'Oggetto riflesso' ],
    'move_down': [ 'Nach unten bewegen', 'Move down', 'Vers le bas', 'Mover hacia abajo', 'Mover para baixo', 'Sposta in basso' ],
    'move_left': [ 'Nach links bewegen', 'Move left', 'Vers la gauche', 'Mover a la izquierda', 'Mover para a esquerda', 'Sposta a sinistra' ],
    'move_right': [ 'Nach rechts bewegen', 'Move right', 'Vers à droite', 'Mover a la derecha', 'Mover para a direito', 'Sposta a destra' ],
    'move_up': [ 'Nach oben bewegen', 'Move up', 'Vers le haut', 'Mover hacia arriba', 'Mover para cima', 'Sposta in alto' ],
    'nav': [ 'Zeige Zoom-Steuerung / Navigation', 'Show Zoom / Navigation controls', 'Montrer navigation', 'Exhibir navegación', 'Exibir navegação', 'Controlli Zoom e Navigazione' ],
    'navtoolprop': [ 'Zeichenfläche- / Objekt-Eigenschaften', 'Board / Object Properties', 'Propriété zone dessin / objets', 'Propiedades del plano ó de un objeto', 'Propriedades da Janela de Visualização / Objeto', 'Proprietà del piano e degli oggetti' ],
    'neu': [ 'Neu', 'New', 'Nouveau', 'Nuevo', 'Novo', 'Nuovo' ],
    'newConst': [ 'Neue Konstruktion anlegen', 'Create new construction', 'Créer une nouvelle construction', 'Crear una nueva construcción', 'Criar uma nova contrução', 'Nuova costruzione' ],
    'newfoldername': [ 'Name des neuen Ordners', 'Name of the new folder', 'Nom du nouveau dossier', 'Nombre de la nueva carpeta', 'Dê um nome para o novo diretório', 'Nome della nuova cartella' ],
    'nextmark': [ 'Nächste Marke', 'Next mark', 'Marque suivante', 'Siguiente marca', 'Próxima marca', 'Prossimo indicatore' ],
    'none': [ 'Keiner', 'None', 'Aucun', 'Ninguno', '', 'Nessuno' ],
    'normal': [ 'Senkrechte', 'Perpendicular', 'Perpendiculaire', 'Perpendicular', 'Perpendicular', 'Perpendicolare' ],
    'of': [ 'von', 'of', 'de', 'de', 'de', 'di' ],
    'ok': [ 'Ok', 'Ok', 'OK', '', '', 'OK' ],
    'ok_return': [ 'Ok + Return', 'Ok + Return', 'Valider', '', '', 'Salva ed esci' ],
    'parallel': [ 'Parallele', 'Parallel', 'Parallèle', 'Paralelo(a)', 'Paralelo', 'Parallela' ],
    'paste_ablation_instruct': [ 'Ziehe das Objekt zum Abtragen an den gewünschten Ort.', 'Release your finger / the mouse button, to paste the copy.', 'Relâcher le doigt ou le bouton souris pour coller la copie.', 'Levante su dedo (suelte el botón del mouse) para pegar', 'Levante o seu dedo / botão do mouse para colar.', 'Rilascia per incollare' ],
    'paste_instruct': [ 'Markiere den gewünschten Ort für die Kopie.', 'Click on the board to paste the copy.', 'Cliquer sur la zone de dessin pour coller la copie.', 'Clic en el plano para pegar la copia', 'Clique na janela de visualização para colar.', 'Clicca sullo schermo per incollare' ],
    'perpendicularBisector': [ 'Mittelsenkrechte', 'Perpendicular Bisector', 'Médiatrice', 'Mediatriz', 'Mediatriz', 'Asse di simmetria' ],
    'plus': [ 'Erhöhen', 'Increase', 'Augmenter', 'Incrementa', 'Aumentar', 'Aumenta' ],
    'point_coord': [ 'X- / Y-Koordinaten', 'X / Y coordinates', 'Coordonnées x/y', 'Coordenadas X/Y', 'Coordenadas X / Y', 'Coordinate x, y' ],
    'point_face': [ 'Symbol', 'Face', 'Rendu', 'Cara', 'Tipo', 'Aspetto' ],
    'point_style': [ 'Punktform', 'Point style', 'Style de point', 'Estilo de punto', 'Tipo do ponto', 'Stile' ],
    'poly': [ 'Polygon', 'Polygon', 'Polygone', 'Polígono', 'Polígono', 'Poligono' ],
    'polygon_selection': [ 'Markiere nacheinander alle Eckpunkte und zum Abschluss wieder den Anfangspunkt.', 'Select the points which should span the polygon. Finalize the selection by clicking another time on the first point.', 'Sélectionner les points qui forment le polygone. Finir la sélection en cliquant à nouveau sur le 1er point.', 'Seleccione los vértices que conformarán ', 'Selecione os pontos que gerarão o polígono. Finalize a seleção clicando uma outra vez no primeiro ponto.', 'Seleziona i vertici del poligono; completa cliccando sul primo punto' ],
    'precision': [ 'Dezimalstellen', 'Decimal places', 'Décimales', 'Decimales', '', 'Posizioni decimali' ],
    'prevmark': [ 'Vorherige Marke', 'Previous mark', 'Marque précédente', 'Marca anterior', 'Marca anterior', 'Indicatore precedente' ],
    'prop_instruct': [ 'Klicke auf das Objekt, das bearbeitet werden soll.', 'Click on the object you want to modify.', 'Cliquer sur l\'objet à modifier.', 'Clic en el objeto que desea modificar', 'Clique no objeto que você deseja modificar.', 'Clicca sull\'oggetto da modificare' ],
    'quadrilateral': [ 'Viereck', 'Quadrilateral', 'Quadrilatère', 'Cuadrilátero', 'Quadrilátero', 'Quadrilatero' ],
    'radius': [ 'Radius', 'Radius', 'Rayon', 'Radio', 'Raio', 'Raggio' ],
    'ray': [ 'Halbgerade', 'Ray', 'Demi-droite', 'Rayo', 'Semirreta', 'Semiretta' ],
    'recognize': [ 'Starte Erkennung', 'Start Recognition', 'Démarrer la reconnaissance', '', '', 'Inizia a riconoscere' ],
    'reflect': [ 'Spiegelung', 'Reflection', 'Réflexion', 'Reflexión', 'Reflexão', 'Riflessione' ],
    'reflectedPoint': [ 'Gespiegelter Punkt', 'Reflected Point', 'Point réfléchi', '', '', 'Punto riflesso' ],
    'regular': [ 'Regelmäßiges', 'Regular', 'Régulier', 'Regular', 'Regular', 'Regolare' ],
    'reg_polygon_selection': [ 'Markiere zwei Punkte zum Festlegen einer Polygonseite.', 'Select two board points, which will act as anchors<br>for the regular polygon being created.', 'Sélectionner 2 points qui serviront d\'ancres pour créer un polygone régulier.', 'Seleccione dos puntos que serán los vértices iniciales del polígono regular', 'Selecione dois pontos que servirão como vértices para o polígono regular.', 'Seleziona due punti del piano che costituirenno il lato del poligono regolare' ],
    'remove': [ 'Löschen', 'Delete', 'Effacer', 'Eliminar', 'Apagar', 'Elimina' ],
    'reset': [ 'Zurücksetzen', 'Reset', 'Réinitialiser', 'Reiniciar', 'Reiniciar', 'Reset' ],
    'right': [ 'Rechts', 'Right', 'Droite', 'Derecha', 'Direita', 'Destra' ],
    'right_angle': [ 'Zeige 90° Punkt', 'Show 90° dot', 'Montre 90° point', 'Exhibir 90° punto', 'Exibir 90° ponto', 'Mostra un punto per l\'angolo retto' ],
    'ruler': [ 'Lineal', 'Ruler', 'Règle', 'La regla', '', 'Righello' ],
    'ruler_selection': [ 'Markiere eine Stelle auf der Zeichenfläche, um den Anfangspunkt des Lineals zu platzieren.', 'Mark a position on the board to place the starting point of the ruler.', 'Cliquer à 2 endroits de la zone de dessin pour placer les points de début et de fin de la règle.', '', '', 'Indica una posizione sullo schermo per collocare la posizione iniziale del righello' ],
    'sect': [ 'Sektor', 'Sector', 'Secteur', 'Sector', 'Setor', 'Settore' ],
    'sectordot': [ 'Punkt', 'Dot', 'Point', 'Punto', '', 'Punto' ],
    'sector_measure': [ 'Bogenlänge messen', 'Measure arc', 'Mesurer un arc', 'Medir arco', 'Medir arco', 'Misura l\'arco' ],
    'sector_related_measure': [ 'Bogenlänge', 'Arc length', 'Longueur de larc', 'Longitud de arco', 'Comprimento de arco', 'Lunghezza dell\'arco' ],
    'selectIntersection': [ 'Markiere Schnittpunkt', 'Select an intersection:', 'Sélectionner une intersection', 'Seleccionar una intersección', 'Selecionar uma interseção:', 'Seleziona un\'intersezione' ],
    'select_transform': [ 'Transformation auswählen', 'Select a transformation', 'Sélectionner une transformation', 'Seleccionar una transformación', 'Selecionar uma transformação:', 'Seleziona una trasformazione' ],
    'settings': [ 'Optionen', 'Settings', 'Paramètres', 'Ajustes', 'Configurações', 'Configura' ],
    'shift': [ 'Shift', 'Shift', 'MAJ/min', '', '', 'Maiusc.' ],
    'show_tooltips': [ 'Zeige Tooltips', 'Show tooltips', 'Montrer les infobulles', 'Mostrar sugerencias', 'Exibir dicas', 'Mostra i suggerimenti' ],
    'slide': [ 'Regler', 'Slider', 'Curseur', 'Deslizdor', 'Controle deslizante', 'Cursore' ],
    'slidelist': [ 'Slider-Liste', 'Slider list', 'Liste du curseur', '', '', 'Elenco dei cursori' ],
    'slider_initialization': [ 'Regler-Initialisierung', 'Slider initialization:', 'Initiale du curseur', 'Definir valores inicial y final del deslizador', 'Definir as extremidades e o valor inicial do controle deslizante.', 'Inizializzazione del cursore' ],
    'slider_placement': [ 'Markiere zur Platzierung des Reglers eine Stelle auf der Zeichenfläche.', 'Click on one place on the board to place the slider.', 'Cliquer à un endroit de la zone de dessin pour placer le curseur.', 'Clic en dos lugares del plano para ubicar eldeslizador', 'Clique em dois lugares para colocar o controle deslizante.', 'Clicca su un punto del piano per collocare un cursore' ],
    'slider_value': [ 'Wert des Schiebereglers', 'Slider value', 'Valeur du curseur', 'Valor del deslizador', 'Valor do controle deslizante', 'Valore del cursore' ],
    'slopetriangle': [ 'Steigungsdreieck', 'Slopetriangle', 'Triangle de pente', '', '', 'Inclinazione' ],
    'snap_to_grid': [ 'Einrasten auf Gitter', 'Snap to grid', 'Capturer à la grille', 'Fijar cuadrícula', 'Ajustar à malha', 'Vincola alla griglia' ],
    'snap_to_point': [ 'Einrasten auf Punkt', 'Snap to point', 'Capturer au point', 'Fijar punto', 'Ajustar ao ponto', 'Vincola al punto' ],
    'sound': [ 'Audio', 'Sound', 'Son', 'Sonido', 'Som', 'Suono' ],
    'square': [ 'Quadrat', 'Square', 'Carré', 'Cuadrado', '', 'Quadrato' ],
    'startEnd': [ 'Start- / Endpunkt', 'Start / end point', 'Point de début/fin', '', '', 'Punti iniziale e finale' ],
    'start_value': [ 'Startwert', 'Start value', '', '', '', 'Valore iniziale' ],
    'status_fix': [ 'Fixieren', 'Fix', 'Fixer', 'Fijar', 'Fixar', 'Fissa' ],
    'stickyLabel': [ 'Angeheftetes Label', 'Sticky Label', 'Étiquette', '', '', 'A distanza fissa' ],
    'store_matrix': [ 'Matrix speichern', 'Store matrix', 'Enregistrer la matrice', 'Matriz de almacenmiento', 'Matriz', 'Salva la matrice' ],
    'stroke_settings': [ 'Stricheigenschaften', 'Stroke settings', 'Paramètres des traits', 'Ajustes de trazo', 'Configurações', 'Spessore' ],
    'stroke_width': [ 'Strichstärke', 'Stroke width', 'Epaisseur', 'Ajustes de ancho', 'Espessura', 'Spessore' ],
    'tangent': [ 'Tangente', 'Tangent', 'Tangente', 'Tangente', 'Tangente', 'Tangente' ],
    'text_element': [ 'Text', 'Text', 'Texte', 'Texto', 'Texto', 'Testo' ],
    'text_placement': [ 'Markiere eine Stelle auf der Zeichenfläche<br>zum Platzieren des Textes.', 'Click on the board to place your text.', 'Cliquer sur la zone de dessin pour place le texte', 'Clic en el plano para colocar su texto', 'Clique na janela de visualização para colocar o seu texto.', 'Clicca sul piano per collocare un testo' ],
    'text_size': [ 'Textgröße', 'Label size', 'Taille étiquette', 'Tamaño del rótulo', 'Tamanho do rótulo', 'Dimensione' ],
    'ticks': [ 'Ticks', 'Ticks', 'Point dintervalle', 'Marcas', 'Marcas', 'Spunta' ],
    'to': [ 'zu', 'to', 'vers', 'para', 'para', 'verso' ],
    'togglemark': [ 'Setze / Entferne Marke', '(Un-)Set mark', '(Dé)Faire une marque', 'Fijar(soltar) marcas', 'Definir / remover marca', 'Assegna' ],
    'toolbarposition': [ 'Toolbar Position', 'Toolbar position', 'Position de la barre d\'outils', 'Posición de la barra de herramientas', 'Posição da barra de ferramentas', 'Posizione della barra degli strumenti' ],
    'tools': [ 'Werkzeug-Menü', 'Tools menu', 'Menu des outils', 'Menú herramientas', 'Menu de ferramentas', 'Menù degli strumenti' ],
    'tools_function': [ 'Plot', 'Plot', 'Tracer', 'Graficar', 'Gráfico', 'Grafico' ],
    'tools_regpolygon': [ 'Reg. Pol.', 'Reg. pol.', 'Pol. rég.', 'Pol. reg.', 'Pol. Reg.', 'Pol. regol.' ],
    'top': [ 'Oben', 'Top', 'Haut', 'Arriba', 'Em cima', 'Sopra' ],
    'trace': [ 'Spur', 'Trace', 'Trace', 'Traza', 'Traço', 'Traccia' ],
    'transform_apply': [ 'Markiere den Punkt, der transformiert werden soll.', 'Click on a point on which the transformation should be applied', 'Cliquer sur le point à transformer', 'Clic en objeto donde la transformación será aplicada', 'Clique no ponto que será transformado', 'Clicca su un punto da trasformare' ],
    'transform_objects': [ 'Objekte transformieren', 'Transform objects', 'Transformer des objets', 'Transformar objetos', 'Transformar objetos', 'Trasforma oggetti' ],
    'triangle': [ 'Dreieck', 'Triangle', 'Triangle', 'Triángulo', 'Triângulo', 'Triangolo' ],
    'turtle': [ 'Turtle', 'Turtle', 'Tortue', 'Tortuga', 'Tartaruga', 'Tartaruga' ],
    'unknown': [ 'Unbekannt', 'Unknown', 'Inconnu', 'Desconocido', '', 'Sconosciuto' ],
    'unsupported_file_format': [ 'Dateiformat wird nicht unterstützt!', 'Unsupported file format', 'Format de fichier non supporté', 'formato de archivo no soportado', 'Formato de arquivo não suportado', 'Formato di file non supportato' ],
    'untitled': [ 'Unbenannt', 'Untitled', 'Sans titre', 'Sin título', 'Sem título', 'Senza titolo' ],
    'upload': [ 'Hochladen', 'Upload', 'Téléverser', 'Subir', 'Transferir', 'Carica' ],
    'uploadsuccess': [ 'Export erfolgreich', 'Upload successful.', 'Téléversé avec succès.', 'Subida exitosa', 'Transferência realizada com êxito', 'Caricamento avvenuto' ],
    'valueRange': [ 'Wertebereich', 'Value range', 'Intervalle de valeur', '', '', 'Valori dell\'intervallo' ],
    'vect': [ 'Vektor', 'Vector', 'Vecteur', 'Vector', 'Vetor', 'Vettore' ],
    'vibration': [ 'Vibration', 'Vibration', 'Vibration', 'Vibración', 'Vibração', 'Vibrazione' ],
    'volume': [ 'Lautstärke', 'Volume', 'Volume', 'Volumen', 'Volume', 'Volume' ],
    'zoomLevel': [ 'Zoom-Stufe', 'Zoom level', 'Niveau de zoom', '', '', 'Livello di zoom' ],
    'zoom_100': [ 'Standard-Zoom', 'Default Zoom', 'Zoom par défaut', 'Vista estándar', 'Zoom Padrão', 'Zoom di default' ],
    'zoom_in': [ 'Zoom In', 'Zoom In', 'Agrandir', 'Acercar', 'Ampliar', 'Zoom +' ],
    'zoom_out': [ 'Zoom Out', 'Zoom Out', 'Réduire', 'Alejar', 'Reduzir', 'Zoom -' ]
};